export type YouTubeLegendEpisode = {
  ep: number;
  episodeLabel?: string;
  home: string;
  away: string;
  stage?: string;
  date?: string;
  score: string | null;
  hook: string;
  story: string;
  youtube: string;
  imageTeam?: string;
};

export type YouTubeLegendBonusVideo = {
  id: string;
  episode: number;
  episodeLabel: string;
  kind?: "bonus" | "series";
  title: string;
  subtitle: string;
  teams: string;
  story: string;
  youtube: string;
  alternateYoutube?: string[];
  imageTeam?: string;
};

export type YouTubeDidYouKnowShort = {
  id: string;
  episode: number;
  episodeLabel: string;
  title: string;
  subtitle: string;
  teams: string;
  story: string;
  youtube: string | null;
  imageTeam?: string;
};

export const YOUTUBE_LEGEND_EPISODES: YouTubeLegendEpisode[] = [
  {
    ep: 1,
    home: "Mexico",
    away: "South Africa",
    stage: "Group A - Matchday 1",
    date: "Jun 11, 2026 - Estadio Azteca",
    score: "0-0",
    hook: "The Azteca's ghosts and the unfinished business of 2010.",
    story:
      "Opening night belongs to pressure, memory, and noise. Mexico walk into the Azteca with history on their shoulders, while South Africa carry the spirit of Soccer City into another first chapter.",
    youtube: "https://www.youtube.com/watch?v=myNgytIwZ0U",
    imageTeam: "Mexico",
  },
  {
    ep: 2,
    home: "South Korea",
    away: "Czechia",
    stage: "Group A",
    score: "1-0",
    hook: "Son's last dance begins under the Guadalajara lights.",
    story:
      "South Korea's goodbye story begins with speed, sacrifice, and one final run from Son. Czechia arrive with old tournament muscle, ready to turn sentiment into silence.",
    youtube: "https://www.youtube.com/watch?v=53d_4pQcY_8",
    imageTeam: "South Korea",
  },
  {
    ep: 3,
    home: "Canada",
    away: "Bosnia & Herzegovina",
    stage: "Group B",
    score: "0-0",
    hook: "The Maple Leaf Man turns Toronto into a wall of red.",
    story:
      "Canada's home crowd searches for a moment that can outlive the match. Bosnia bring old scars, pride, and the calm of a team that knows how to suffer without bending.",
    youtube: "https://www.youtube.com/watch?v=qicbV-pTVdM",
    imageTeam: "Canada",
  },
  {
    ep: 4,
    home: "USA",
    away: "Paraguay",
    stage: "Group D",
    score: "1-1",
    hook: "The 1930 secret America forgot returns under a modern roof.",
    story:
      "The USA carry a forgotten rematch into a stadium built for noise. Paraguay answer with defiance, distance shooting, and a reminder that history rarely stays buried.",
    youtube: "https://www.youtube.com/watch?v=Rzi_0xhjrF4",
    imageTeam: "USA",
  },
  {
    ep: 5,
    home: "Brazil",
    away: "Morocco",
    stage: "Group C",
    score: "1-0",
    hook: "Brazil's kings meet Morocco's revenge story.",
    story:
      "Brazil chase beauty and a sixth star, but Morocco arrive with 2022 still burning in their boots. The kings have a secret, and the Atlas Lions know where to press.",
    youtube: "https://www.youtube.com/watch?v=hoOs2h5Jzms",
    imageTeam: "Brazil",
  },
  {
    ep: 6,
    home: "Argentina",
    away: "Algeria",
    stage: "Group J",
    score: null,
    hook: "Messi and Algeria share a night haunted by betrayal and miracles.",
    story:
      "Argentina's last dance meets Algeria's old football wound. Two ghosts walk beside the pitch, waiting for one save, one touch, and one moment that refuses to leave.",
    youtube: "https://www.youtube.com/watch?v=j57_mVzWGXg",
    imageTeam: "Argentina",
  },
  {
    ep: 7,
    home: "Brazil",
    away: "Haiti",
    stage: "Group C",
    score: "4-1",
    hook: "The supermarket worker who shocked Brazil walks into the legend.",
    story:
      "Brazil expect a procession, but Haiti bring rhythm, memory, and a goal that turns a mismatch into a story worth repeating. The drumbeat refuses to fade.",
    youtube: "https://www.youtube.com/watch?v=4RxCyLtIccs",
    imageTeam: "Haiti",
  },
  {
    ep: 9,
    home: "Qatar",
    away: "Switzerland",
    stage: "Group B",
    score: "0-1",
    hook: "The desert trap waits for the quiet Swiss machine.",
    story:
      "Qatar set the tempo low and dangerous, asking Switzerland to solve heat, patience, and pride. The Falconer watches every pass before danger arrives.",
    youtube: "https://www.youtube.com/watch?v=8Pf-oRROUyk",
    imageTeam: "Qatar",
  },
  {
    ep: 10,
    home: "Haiti",
    away: "Scotland",
    stage: "Group C",
    score: "1-1",
    hook: "Two underdogs carry fifty years of glorious heartbreak.",
    story:
      "Haiti and Scotland meet where hope hurts most. One nation remembers 1974 drums, the other hears the lone piper, and both know a single goal can become folklore.",
    youtube: "https://www.youtube.com/watch?v=x5N4LiIgXRo",
    imageTeam: "Haiti",
  },
  {
    ep: 11,
    home: "England",
    away: "Ghana",
    stage: "Group L",
    score: "1-1",
    hook: "England's secret meets Ghana's unfinished World Cup pain.",
    story:
      "England bring old invention and new expectation. Ghana bring the memory of the goal Africa was denied, and a belief that one brave clearance can rewrite a continent's night.",
    youtube: "https://www.youtube.com/watch?v=zWAcb4CLOWs",
    imageTeam: "South Africa",
  },
  {
    ep: 12,
    home: "Australia",
    away: "Turkey",
    stage: "Group D",
    score: "2-2",
    hook: "Two nations with no home fight for one place to breathe.",
    story:
      "Australia and Turkey carry migration, distance, and survival in the same match. The Wanderer card belongs to the team that keeps moving when the path closes.",
    youtube: "https://www.youtube.com/watch?v=gGOqgKEG10o",
    imageTeam: "Australia",
  },
  {
    ep: 13,
    home: "Germany",
    away: "Curacao",
    stage: "Group E",
    score: "3-0",
    hook: "The island of 150,000 meets the German machine.",
    story:
      "Germany arrive like a machine built from tournaments. Curacao answer with the courage of the smallest nation in the room, asking the giant to notice every save.",
    youtube: "https://www.youtube.com/watch?v=uKZ5R7vlBi8",
    imageTeam: "USA",
  },
  {
    ep: 14,
    home: "Netherlands",
    away: "Japan",
    stage: "Group F",
    score: "2-2",
    hook: "Total Football meets the Samurai spirit.",
    story:
      "The Netherlands bring geometry and old orange swagger. Japan bring discipline, speed, and the memory of beating giants who thought the match was already solved.",
    youtube: "https://www.youtube.com/watch?v=vKJ1O2sNV1Y",
    imageTeam: "South Korea",
  },
  {
    ep: 15,
    home: "Ivory Coast",
    away: "Ecuador",
    stage: "Group E",
    score: "1-1",
    hook: "The footballer who helped stop a war watches the touchline.",
    story:
      "Ivory Coast bring a story bigger than sport, where football once helped quiet a nation. Ecuador answer with altitude, speed, and a defence that does not flinch.",
    youtube: "https://www.youtube.com/watch?v=3GRncnYwQVw",
    imageTeam: "Brazil",
  },
  {
    ep: 16,
    home: "Sweden",
    away: "Tunisia",
    stage: "Group F",
    score: "2-1",
    hook: "The team that opened Africa's door walks into Nordic frost.",
    story:
      "Sweden bring cold control and a striker's hunger. Tunisia bring the fire of a continent's first World Cup win, still glowing beneath the desert shirt.",
    youtube: "https://www.youtube.com/watch?v=gGZPOt2H_0s",
    imageTeam: "Morocco",
  },
  {
    ep: 17,
    home: "Spain",
    away: "Cape Verde",
    stage: "Group H",
    score: "3-1",
    hook: "Half a million people step onto Spain's stage.",
    story:
      "Spain bring an empire of passes and patience. Cape Verde bring a first World Cup night, an island heartbeat, and the dangerous freedom of having everything to gain.",
    youtube: "https://www.youtube.com/watch?v=_vHQqJxt6G4",
    imageTeam: "Mexico",
  },
  {
    ep: 18,
    home: "Belgium",
    away: "Egypt",
    stage: "Group G",
    score: "2-1",
    hook: "The number one team that never won faces the Pharaoh king.",
    story:
      "Belgium carry the last glow of a golden generation. Egypt carry Salah's crown and the question every great player hears near the end: can one more night be enough?",
    youtube: "https://www.youtube.com/watch?v=R1r8n4D7BTg",
    imageTeam: "Morocco",
  },
  {
    ep: 19,
    home: "Saudi Arabia",
    away: "Uruguay",
    stage: "Group H",
    score: "1-2",
    hook: "Three million people once silenced two hundred thousand.",
    story:
      "Saudi Arabia remember the shock that humbled Argentina. Uruguay remember the Maracanazo, when a small nation turned a giant stadium silent. This match is built from nerve.",
    youtube: "https://www.youtube.com/watch?v=a8xvaJWZhrs",
    imageTeam: "Qatar",
  },
  {
    ep: 20,
    home: "Iran",
    away: "New Zealand",
    stage: "Group G",
    score: "1-1",
    hook: "The team that went home unbeaten returns to the world stage.",
    story:
      "Iran bring pressure and pride. New Zealand bring the memory of 2010, when they left a World Cup unbeaten while champions fell around them.",
    youtube: "https://www.youtube.com/watch?v=0NFA-yDOlf4",
    imageTeam: "South Korea",
  },
  {
    ep: 21,
    home: "France",
    away: "Senegal",
    stage: "Group I",
    score: "2-1",
    hook: "The debutants who knocked out the champions meet France again.",
    story:
      "France enter with depth everywhere. Senegal enter with the ghost of 2002 dancing beside them, reminding every champion that one brave opener can change history.",
    youtube: "https://www.youtube.com/watch?v=dRK7UPQGzFQ",
    imageTeam: "Morocco",
  },
  {
    ep: 22,
    home: "Iraq",
    away: "Norway",
    stage: "Group I",
    score: "1-1",
    hook: "The war-torn nation that became champions of Asia meets Haaland.",
    story:
      "Iraq carry one flag through old wounds and impossible unity. Norway answer with northern power, Odegaard's control, and Haaland waiting for one clean ball.",
    youtube: "https://www.youtube.com/watch?v=tEURjCad3aY",
    imageTeam: "South Africa",
  },
  {
    ep: 23,
    home: "Austria",
    away: "Jordan",
    stage: "Group J",
    score: "2-1",
    hook: "The tiny kingdom reaches its first World Cup.",
    story:
      "Austria bring old European ghosts and the memory of the Wunderteam. Jordan bring the joy of first arrival, where every tackle feels like proof they belong.",
    youtube: "https://www.youtube.com/watch?v=sbW4Vjt89XY",
    imageTeam: "Qatar",
  },
  {
    ep: 24,
    home: "Portugal",
    away: "DR Congo",
    stage: "Group K",
    score: "3-1",
    hook: "The free kick the world got wrong returns to haunt Portugal.",
    story:
      "Portugal chase the last golden chapter. DR Congo bring the Leopards' old roar and a piece of football history that still feels unresolved.",
    youtube: "https://www.youtube.com/watch?v=uYP2OQxkyA4",
    imageTeam: "Portugal",
  },
  {
    ep: 25,
    home: "England",
    away: "Croatia",
    stage: "Group L",
    score: "2-1",
    hook: "The tiny nation that broke England's dream comes back.",
    story:
      "England meet the checkerboard ghost of 2018. Croatia bring Modric's old calm and the knowledge that small nations can still make giants tremble.",
    youtube: "https://www.youtube.com/watch?v=XthcG-jo4nc",
    imageTeam: "USA",
  },
  {
    ep: 26,
    home: "Ghana",
    away: "Panama",
    stage: "Group L",
    score: "2-1",
    hook: "One kick from history brings Ghana back to the edge.",
    story:
      "Ghana carry the ache of a goal Africa was denied. Panama bring fight, noise, and a chance to make someone else's old wound hurt again.",
    youtube: "https://www.youtube.com/watch?v=q5FyP7kqn_Y",
    imageTeam: "South Africa",
  },
  {
    ep: 27,
    home: "Uzbekistan",
    away: "Colombia",
    stage: "Group K",
    score: "1-2",
    hook: "Twenty years in the cold, and the match FIFA ordered replayed.",
    story:
      "Uzbekistan arrive carrying decades of near misses. Colombia bring rhythm, belief, and the kind of attacking joy that can turn a first-timer's dream into panic.",
    youtube: "https://www.youtube.com/watch?v=RfZIdYYQMF0",
    imageTeam: "Canada",
  },
  {
    ep: 28,
    home: "Czechia",
    away: "South Africa",
    stage: "Group A",
    score: "1-1",
    hook: "The penalty he named the goal that woke a continent.",
    story:
      "Czechia bring structure and tournament memory. South Africa bring 2010 noise, the continent's first World Cup heartbeat, and a belief that joy can score.",
    youtube: "https://www.youtube.com/watch?v=MvIh3oTqD8U",
    imageTeam: "South Africa",
  },
  {
    ep: 29,
    home: "Switzerland",
    away: "Bosnia & Herzegovina",
    stage: "Group B",
    score: "2-1",
    hook: "Born from the same war, two nations share one football story.",
    story:
      "Switzerland and Bosnia meet across memory, migration, and identity. The match feels less like strangers colliding and more like history looking in a mirror.",
    youtube: "https://www.youtube.com/watch?v=tC_s4X28xIo",
    imageTeam: "Bosnia and Herzegovina",
  },
  {
    ep: 30,
    home: "Canada",
    away: "Qatar",
    stage: "Group B",
    score: "2-1",
    hook: "Two World Cup hosts carry opposite curses into one game.",
    story:
      "Canada chase the lift of home soil. Qatar chase respect after hosting without the story they wanted. One host learns what the other still fears.",
    youtube: "https://www.youtube.com/watch?v=aDHiYekaNSE",
    imageTeam: "Canada",
  },
  {
    ep: 31,
    home: "Mexico",
    away: "South Korea",
    stage: "Group A",
    score: "2-1",
    hook: "It took both of them to kill the champions.",
    story:
      "Mexico and South Korea share a strange World Cup thread: nights when giants fell and the script tore open. Now they meet with that same chaos waiting.",
    youtube: "https://www.youtube.com/watch?v=uWC0hQVGYSQ",
    imageTeam: "Mexico",
  },
  {
    ep: 32,
    home: "USA",
    away: "Australia",
    stage: "Group D",
    score: "2-1",
    hook: "The Miracle on Grass returns when amateurs humbled the masters.",
    story:
      "The USA carry one of football's oldest shocks into a modern home game. Australia bring distance, toughness, and the refusal to be impressed by the stage.",
    youtube: "https://www.youtube.com/watch?v=6Y0tMk7FqmE",
    imageTeam: "USA",
  },
  {
    ep: 33,
    home: "Scotland",
    away: "Morocco",
    stage: "Group C",
    score: null,
    hook: "The team that never lost and still went home meets Morocco's miracle.",
    story:
      "Scotland carry the old cruelty of goal difference. Morocco carry the first African semifinal run. One team remembers being unbeaten; the other remembers being impossible.",
    youtube: "https://www.youtube.com/watch?v=VCJPzek1eQE",
    imageTeam: "Morocco",
  },
  {
    ep: 34,
    home: "Turkey",
    away: "Paraguay",
    stage: "Group D",
    score: null,
    hook: "Ten seconds, and the fastest goal in World Cup history.",
    story:
      "Turkey bring the memory of a goal that arrived before the match could breathe. Paraguay bring stubborn South American bite and a talent for ruining rhythm.",
    youtube: "https://www.youtube.com/watch?v=pfebz7jf3ts",
    imageTeam: "Paraguay",
  },
  {
    ep: 35,
    home: "Netherlands",
    away: "Sweden",
    stage: "Group F",
    score: null,
    hook: "The greatest team that never won meets Sweden's new hunger.",
    story:
      "The Netherlands carry beauty, finals, and old heartbreak. Sweden arrive with power up front and the confidence to make another elegant team feel mortal.",
    youtube: "https://www.youtube.com/watch?v=JqDq9e_khdY",
    imageTeam: "South Korea",
  },
  {
    ep: 36,
    home: "Germany",
    away: "Ivory Coast",
    stage: "Group E",
    score: null,
    hook: "The footballer who stopped a war stands against the machine.",
    story:
      "Germany bring tournament order. Ivory Coast bring a story where football once mattered beyond the scoreboard, and every orange shirt carries that memory forward.",
    youtube: "https://www.youtube.com/watch?v=ZsYk3qXKaw0",
    imageTeam: "Brazil",
  },
  {
    ep: 37,
    home: "Ecuador",
    away: "Curacao",
    stage: "Group E",
    score: null,
    hook: "The smallest nation ever at a World Cup holds a continent.",
    story:
      "Ecuador bring altitude legs and serious pressure. Curacao bring the impossible scale of their own arrival, small enough to be counted and brave enough to be feared.",
    youtube: "https://www.youtube.com/watch?v=5wMJTGeEF7E",
    imageTeam: "USA",
  },
  {
    ep: 38,
    home: "Japan",
    away: "Tunisia",
    stage: "Group F",
    score: null,
    hook: "The Samurai and the Eagle fight for one door.",
    story:
      "Japan bring the patience of a team that waits for the 91st minute. Tunisia bring desert pride and the memory of opening a door for Africa.",
    youtube: "https://www.youtube.com/watch?v=ZhZfuu3T2yc",
    imageTeam: "South Korea",
  },
  {
    ep: 39,
    home: "Spain",
    away: "Saudi Arabia",
    stage: "Group H",
    score: null,
    hook: "The ghost of 2022 returns to the scene of football's greatest shock.",
    story:
      "Spain bring the ball and the burden of control. Saudi Arabia bring the memory of the day Argentina fell, and the belief that shock can be rehearsed.",
    youtube: "https://www.youtube.com/watch?v=FGKu0WJ0lp0",
    imageTeam: "Qatar",
  },
  {
    ep: 40,
    home: "Belgium",
    away: "Iran",
    stage: "Group G",
    score: null,
    hook: "The assassin needs one chance; the architect builds a hundred.",
    story:
      "Belgium move through craft and invention. Iran wait for the one ruthless chance that turns a careful match into a knife-edge story.",
    youtube: "https://www.youtube.com/watch?v=Lt-3gH1Ssm4",
    imageTeam: "Morocco",
  },
  {
    ep: 41,
    home: "Uruguay",
    away: "Cape Verde",
    stage: "Group H",
    score: null,
    hook: "The smallest sharks bare their teeth at Uruguay.",
    story:
      "Uruguay bring old giant energy from a small population. Cape Verde answer with island defiance, proving small can mean concentrated, not weak.",
    youtube: "https://www.youtube.com/watch?v=-sHkBq0kyP8",
    imageTeam: "South Africa",
  },
  {
    ep: 42,
    home: "Egypt",
    away: "New Zealand",
    stage: "Group G",
    score: null,
    hook: "The King's last dance meets the unbeaten memory.",
    story:
      "Egypt carry Salah's final chase into a match that cannot waste chances. New Zealand bring the calm of a team that once refused to lose at all.",
    youtube: "https://www.youtube.com/watch?v=qZFXBnqxdE8",
    imageTeam: "Morocco",
  },
  {
    ep: 43,
    home: "Argentina",
    away: "Austria",
    stage: "Group J",
    score: null,
    hook: "Messi's genius meets the machine.",
    story:
      "Argentina bring one last genius chapter. Austria bring structure, old ghosts, and the machine-like patience to ask whether magic still has enough time.",
    youtube: "https://www.youtube.com/watch?v=SmHGZMbrOv4",
    imageTeam: "Argentina",
  },
  {
    ep: 44,
    home: "France",
    away: "Iraq",
    stage: "Group I",
    score: null,
    hook: "The Boy Named After Zidane.",
    story:
      "France and Iraq step into a WorldCup26 Legends chapter called the boy named after Zidane. The card keeps the YouTube story alive inside the album, ready for Brian voice playback and collector unlocks.",
    youtube: "https://www.youtube.com/watch?v=Snndr8qa0o0",
    imageTeam: "Morocco",
  },
  {
    ep: 45,
    home: "Norway",
    away: "Senegal",
    stage: "Group I",
    score: null,
    hook: "The Sock-Ball and The Viking.",
    story:
      "Norway and Senegal meet inside a story of improvised childhood football and northern force, where the YouTube episode becomes a collectible card for the album.",
    youtube: "https://www.youtube.com/watch?v=tabIgKf5i9Q",
    imageTeam: "South Africa",
  },
  {
    ep: 46,
    home: "Jordan",
    away: "Algeria",
    stage: "Group J",
    score: null,
    hook: "Brothers of the Sand.",
    story:
      "Jordan and Algeria carry desert pride, first-arrival belief, and old tournament scars into a WorldCup26 Legends chapter built for Brian voice playback.",
    youtube: "https://www.youtube.com/watch?v=8SDxmuH4_H8",
    imageTeam: "Qatar",
  },
  {
    ep: 47,
    home: "Portugal",
    away: "Uzbekistan",
    stage: "Group K",
    score: "2-1",
    hook: "The Monument's Last Dance.",
    story:
      "Portugal bring the monument's final chapter. Uzbekistan bring first-timer hunger, turning the episode into a card about legacy against arrival.",
    youtube: "https://www.youtube.com/watch?v=KtBlYBJjN4E",
    imageTeam: "Portugal",
  },
  {
    ep: 48,
    home: "England",
    away: "Ghana",
    stage: "Group L",
    score: "2-1",
    hook: "The Empire Has to Listen.",
    story:
      "England and Ghana return to a story of power, pain, and one continent demanding to be heard. The card unlocks from the matching YouTube episode.",
    youtube: "https://www.youtube.com/watch?v=duyUYHc5R_I",
    imageTeam: "South Africa",
  },
  {
    ep: 49,
    home: "Panama",
    away: "Croatia",
    stage: "Group L",
    score: "2-1",
    hook: "Courage Meets Granite.",
    story:
      "Panama bring courage into the storm. Croatia answer with granite tournament memory, and the collector card keeps that clash alive in the album.",
    youtube: "https://www.youtube.com/watch?v=RI69OF9ysxs",
    imageTeam: "South Africa",
  },
  {
    ep: 50,
    home: "Colombia",
    away: "DR Congo",
    stage: "Group K",
    score: "2-1",
    hook: "Flair Meets Fire.",
    story:
      "Colombia move with rhythm and invention. DR Congo answer with fire, power, and the old Leopard roar inside a new WorldCup26 Legends card.",
    youtube: "https://www.youtube.com/watch?v=oaPz_CMZhbg",
    imageTeam: "Canada",
  },
  {
    ep: 51,
    home: "Bosnia & Herzegovina",
    away: "Qatar",
    stage: "Group B",
    score: "1-0",
    hook: "The Dragon's Last Fire.",
    story:
      "Bosnia carry one more dragon flame into Qatar's careful game, a chapter about age, pride, and the last sparks of a golden striker's story.",
    youtube: "https://www.youtube.com/watch?v=P4p23g9Z_e8",
    imageTeam: "Bosnia and Herzegovina",
  },
  {
    ep: 52,
    home: "Switzerland",
    away: "Canada",
    stage: "Group B",
    score: "1-1",
    hook: "The General's Last Campaign.",
    story:
      "Switzerland bring tournament discipline. Canada bring home-nation urgency, and the General's last campaign becomes a collectible story beat.",
    youtube: "https://www.youtube.com/watch?v=C7cmGx_LOCc",
    imageTeam: "Canada",
  },
  {
    ep: 53,
    home: "Scotland",
    away: "Brazil",
    stage: "Group C",
    score: "0-3",
    hook: "The Tartan Army Meets the Hexa.",
    story:
      "Scotland bring the Tartan Army's heartbreak and hope. Brazil bring the Hexa dream, making this card a meeting of noise, beauty, and pressure.",
    youtube: "https://www.youtube.com/watch?v=BXDntJbpDZI",
    imageTeam: "Brazil",
  },
  {
    ep: 54,
    home: "Morocco",
    away: "Haiti",
    stage: "Group C",
    score: "2-1",
    hook: "The Lion and the Grenadier.",
    story:
      "Morocco's lion meets Haiti's grenadier spirit in a story of defiance, rhythm, and belief that the card album can replay through Brian's voice.",
    youtube: "https://www.youtube.com/watch?v=NJ9b7bBv4Hc",
    imageTeam: "Morocco",
  },
  {
    ep: 55,
    home: "Mexico",
    away: "Czechia",
    stage: "Group A",
    score: "1-0",
    hook: "The Diamond of Prague Meets the Aztec Sun.",
    story:
      "Mexico's Aztec sun meets Czechia's diamond shape, turning structure and heat into a new live episode card for collectors.",
    youtube: "https://www.youtube.com/watch?v=QmnrOiwgRs8",
    imageTeam: "Mexico",
  },
  {
    ep: 56,
    home: "South Africa",
    away: "South Korea",
    stage: "Group A",
    score: "1-0",
    hook: "Two Sons of the Beautiful Game.",
    story:
      "South Africa and South Korea share a story of speed, sound, and national memory, with two sons of the game carrying the episode into the album.",
    youtube: "https://www.youtube.com/watch?v=O1gRDEhtUZM",
    imageTeam: "South Korea",
  },
  {
    ep: 57,
    home: "Curacao",
    away: "Ivory Coast",
    stage: "Group E",
    score: "1-1",
    hook: "The African-Caribbean Symphony.",
    story:
      "Curacao's island miracle meets Ivory Coast's orange force, and the African-Caribbean rhythm becomes a collector story card.",
    youtube: "https://www.youtube.com/watch?v=94AJ9nrDEJE",
    imageTeam: "Brazil",
  },
  {
    ep: 58,
    home: "Ecuador",
    away: "Germany",
    stage: "Group E",
    score: "1-0",
    hook: "The Equator's Challenge.",
    story:
      "Ecuador bring altitude, speed, and equator nerve. Germany bring the machine, giving collectors a card about a challenge that refuses to bow.",
    youtube: "https://www.youtube.com/watch?v=NIlS14DVEMU",
    imageTeam: "Brazil",
  },
  {
    ep: 59,
    home: "Japan",
    away: "Sweden",
    stage: "Group F",
    score: "1-0",
    hook: "The Art of Precision.",
    story:
      "Japan and Sweden turn patience, timing, and finishing into a precision story where one clean movement can define the card.",
    youtube: "https://www.youtube.com/watch?v=LujOwKeqnEU",
    imageTeam: "South Korea",
  },
  {
    ep: 60,
    home: "Tunisia",
    away: "Netherlands",
    stage: "Group F",
    score: "0-1",
    hook: "The Orange Storm and the Desert Wind.",
    story:
      "The Netherlands bring the orange storm. Tunisia bring desert wind, and their collision becomes a live story card for the WorldCup26 album.",
    youtube: "https://www.youtube.com/watch?v=4MWG1L5JiBE",
    imageTeam: "Morocco",
  },
  {
    ep: 61,
    home: "Paraguay",
    away: "Australia",
    stage: "Group D",
    score: "1-0",
    hook: "The Waltz and the War.",
    story:
      "Paraguay and Australia turn rhythm, distance, and fight into a match story that collectors can hear, open, and save.",
    youtube: "https://www.youtube.com/watch?v=UJmaemaa-gY",
    imageTeam: "Paraguay",
  },
  {
    ep: 62,
    home: "Turkey",
    away: "USA",
    stage: "Group D",
    score: "2-2",
    hook: "Ghosts of Empires.",
    story:
      "Turkey and the USA meet under ghosts of empires, where history, migration, and home pressure turn into a collectible Legend card.",
    youtube: "https://www.youtube.com/watch?v=1WLSQDYGsMo",
    imageTeam: "USA",
  },
  {
    ep: 63,
    home: "Norway",
    away: "France",
    stage: "Group I",
    score: "2-1",
    hook: "The Titans Collide: Mbappe vs Haaland.",
    story:
      "Norway and France carry two modern titans into one frame: Haaland waiting for the ball, Mbappe waiting for space, and collectors waiting for the card.",
    youtube: "https://www.youtube.com/watch?v=u4B2JWTm8pc",
    imageTeam: "USA",
  },
  {
    ep: 64,
    home: "Senegal",
    away: "Iraq",
    stage: "Group I",
    score: "1-0",
    hook: "Two Lions.",
    story:
      "Senegal and Iraq bring two different lions into one episode, each carrying pride, pressure, and a memory bigger than the scoreboard.",
    youtube: "https://www.youtube.com/watch?v=0llU9z8wc_g",
    imageTeam: "Morocco",
  },
  {
    ep: 65,
    home: "Cape Verde",
    away: "Saudi Arabia",
    stage: "Group H",
    score: "1-0",
    hook: "The Believers.",
    story:
      "Cape Verde and Saudi Arabia meet as believers in different miracles, turning conviction into a live WorldCup26 Legends card.",
    youtube: "https://www.youtube.com/watch?v=LU9rX0R14hw",
    imageTeam: "South Africa",
  },
  {
    ep: 66,
    home: "Uruguay",
    away: "Spain",
    stage: "Group H",
    score: "2-1",
    hook: "The Derby of Will vs Art.",
    story:
      "Uruguay bring will, edge, and old scars. Spain bring art, control, and pressure, making this episode a derby of opposite football souls.",
    youtube: "https://www.youtube.com/watch?v=HbxhAFwxv_4",
    imageTeam: "Mexico",
  },
  {
    ep: 67,
    home: "Egypt",
    away: "Iran",
    stage: "Group G",
    score: "1-0",
    hook: "The Desert Derby.",
    story:
      "Egypt and Iran meet in a desert derby where kings, assassins, pride, and patience all wait for one decisive moment.",
    youtube: "https://www.youtube.com/watch?v=k_UwgDqfqBE",
    imageTeam: "Qatar",
  },
  {
    ep: 68,
    home: "Belgium",
    away: "New Zealand",
    stage: "Group G",
    score: "2-1",
    hook: "The Last Stand.",
    story:
      "Belgium bring the last stand of an old golden story. New Zealand bring the memory of refusing to lose, and the card waits at the end.",
    youtube: "https://www.youtube.com/watch?v=PRxE6alq_Qg",
    imageTeam: "Morocco",
  },
  {
    ep: 69,
    home: "Croatia",
    away: "Ghana",
    stage: "Group L",
    score: "0-0",
    hook: "The Warriors.",
    story:
      "Croatia and Ghana bring warriors of different kinds: one hardened by tournament granite, one burning with African memory and unfinished business.",
    youtube: "https://www.youtube.com/watch?v=V_NSSOTMd6w",
    imageTeam: "South Africa",
  },
  {
    ep: 70,
    home: "England",
    away: "Panama",
    stage: "Group L",
    score: "1-1",
    hook: "The Ghost of 2018.",
    story:
      "England and Panama meet with the memory of a six-goal night still floating over the pitch, turning old humiliation and new courage into a rare Legend card.",
    youtube: "https://www.youtube.com/watch?v=iWAJytToqUU",
    imageTeam: "England",
  },
  {
    ep: 71,
    home: "Colombia",
    away: "Portugal",
    stage: "Group K",
    score: "0-0",
    hook: "El Dorado and the two number tens.",
    story:
      "Colombia bring gold, rhythm, and Luis Diaz. Portugal bring monuments, control, and old pressure, turning this episode into a duel of football treasure and pride.",
    youtube: "https://www.youtube.com/watch?v=r0aLa-fTI_Y",
    imageTeam: "Colombia",
  },
  {
    ep: 72,
    home: "DR Congo",
    away: "Uzbekistan",
    stage: "Group K",
    score: "0-1",
    hook: "The Outsiders' Revolt.",
    story:
      "DR Congo and Uzbekistan arrive as outsiders with different fires: one built from power and diaspora, the other from patience and a first great rebellion.",
    youtube: "https://www.youtube.com/watch?v=PPIfQUZNnsc",
    imageTeam: "DR Congo",
  },
  {
    ep: 73,
    home: "Algeria",
    away: "Austria",
    stage: "Group J",
    score: "0-0",
    hook: "The Reckoning.",
    story:
      "Algeria carry an old World Cup wound into a match against Austria, where memory, pressure, and tactical steel turn the episode into a reckoning.",
    youtube: "https://www.youtube.com/watch?v=QGPXwabOoL4",
    imageTeam: "Algeria",
  },
  {
    ep: 74,
    home: "Argentina",
    away: "Jordan",
    stage: "Group J",
    score: "2-0",
    hook: "The First Chapter.",
    story:
      "Argentina bring the weight of champions. Jordan bring the thrill of a first chapter, walking into the story with nothing to lose and everything to collect.",
    youtube: "https://www.youtube.com/watch?v=avVv7YnW8O4",
    imageTeam: "Argentina",
  },
  {
    ep: 75,
    home: "Brazil",
    away: "Japan",
    stage: "Round of 32",
    score: "2-1",
    hook: "Samba vs the Samurai.",
    story:
      "Brazil's rhythm meets Japan's discipline in a card built from beauty, precision, and the feeling that one clean counterattack can silence a giant.",
    youtube: "https://www.youtube.com/watch?v=3ANz7zN_TZI",
    imageTeam: "Brazil",
  },
  {
    ep: 76,
    home: "Germany",
    away: "Paraguay",
    stage: "Round of 32",
    score: "1-0",
    hook: "The Sleeping Giant Wakes.",
    story:
      "Germany bring machinery and memory. Paraguay bring bite and resistance, waiting to find out whether the giant wakes angry or wakes afraid.",
    youtube: "https://www.youtube.com/watch?v=k_n91Jk30-M",
    imageTeam: "Germany",
  },
  {
    ep: 77,
    home: "South Africa",
    away: "Canada",
    stage: "Round of 32",
    score: "1-1 (4-2 pens)",
    hook: "The Storm Birds.",
    story:
      "South Africa and Canada turn speed, sky, and belief into a storm, with two football cultures chasing a card that feels bigger than a group match.",
    youtube: "https://www.youtube.com/watch?v=J0J_4IWae3I",
    imageTeam: "South Africa",
  },
  {
    ep: 78,
    home: "Brazil",
    away: "Japan",
    stage: "Round of 32",
    score: "1-2",
    hook: "The Rising Sun.",
    story:
      "Brazil meet Japan again under a different symbol: the rising sun, a card about discipline, pride, and the moment a precise team refuses to blink.",
    youtube: "https://www.youtube.com/watch?v=YEELViNi2KY",
    imageTeam: "Japan",
  },
  {
    ep: 79,
    home: "Germany",
    away: "Paraguay",
    stage: "Round of 32",
    score: "2-0",
    hook: "The Mountain King.",
    story:
      "Germany and Paraguay climb into a darker myth, where the Mountain King waits above the match and the rare card belongs to the team that survives the height.",
    youtube: "https://www.youtube.com/watch?v=rAb99m2Sf_0",
    imageTeam: "Germany",
  },
  {
    ep: 80,
    home: "Netherlands",
    away: "Morocco",
    stage: "Round of 32",
    score: "1-2",
    hook: "The Atlas Lions.",
    story:
      "The Netherlands face Morocco in a story of orange geometry against mountain pride, where the Atlas Lion guards the final rare card of the current run.",
    youtube: "https://www.youtube.com/watch?v=JnKwpBDpKSI",
    imageTeam: "Morocco",
  },
  {
    ep: 81,
    home: "Ivory Coast",
    away: "Norway",
    stage: "Round of 32",
    score: "1-2",
    hook: "The Wolf and the Elephant.",
    story:
      "Ivory Coast carry the memory of football that once helped quiet a nation, while Norway arrive with northern force and Haaland's shadow. The Elephant and the Wolf turn one match into a test of power, patience, and pride.",
    youtube: "https://www.youtube.com/watch?v=BBM9frfQMLs",
    imageTeam: "Ivory Coast",
  },
  {
    ep: 82,
    home: "France",
    away: "Sweden",
    stage: "Round of 32",
    score: "2-1",
    hook: "The Rooster and the Dragon.",
    story:
      "France bring champions' gravity and a blue shirt that expects the world to bend. Sweden answer with old tournament steel and a dragon story built for the coldest moments.",
    youtube: "https://www.youtube.com/watch?v=01LkHboUrBg",
    imageTeam: "France",
  },
  {
    ep: 83,
    home: "Mexico",
    away: "Ecuador",
    stage: "Round of 32",
    score: "1-2",
    hook: "The Serpent and the Condor.",
    story:
      "Mexico bring the serpent, the stadium thunder, and a history that refuses quiet nights. Ecuador answer with the condor's height, speed, and belief that pressure can become flight.",
    youtube: "https://www.youtube.com/watch?v=n15qQsmdlbc",
    imageTeam: "Mexico",
  },
  {
    ep: 84,
    home: "England",
    away: "DR Congo",
    stage: "Round of 32",
    date: "Jul 1, 2026",
    score: "2-1",
    hook: "Three lions meet the leopard that fears nothing.",
    story:
      "England carry nine hundred years of crest and expectation into the last thirty-two. DR Congo's Leopards arrive silent and fearless — the team no giant wants to meet on a knockout night.",
    youtube: "https://www.youtube.com/watch?v=qND33AsNhr0",
    imageTeam: "England",
  },
  {
    ep: 85,
    home: "Belgium",
    away: "Senegal",
    stage: "Round of 32",
    date: "Jul 1, 2026",
    score: "1-2",
    hook: "The Red Devil meets the Lion of Teranga.",
    story:
      "A golden generation burns to finish its story, but Senegal arrive as kings of a continent. One night, one devil, one lion — and only one of them keeps marching.",
    youtube: "https://www.youtube.com/watch?v=fXlvNARuTYc",
    imageTeam: "Belgium",
  },
  {
    ep: 86,
    home: "USA",
    away: "Bosnia & Herzegovina",
    stage: "Round of 32",
    date: "Jul 1, 2026",
    score: "2-1",
    hook: "The eagle and the dragon collide on home soil.",
    story:
      "The bald eagle soars over a nation hosting the world, while Bosnia's dragons come down from the Balkans unafraid. The hosts' first knockout test arrives breathing fire.",
    youtube: "https://www.youtube.com/watch?v=DJX6iFxc_8g",
    imageTeam: "USA",
  },
  {
    ep: 87,
    home: "Spain",
    away: "Austria",
    stage: "Round of 32",
    date: "Jul 2, 2026",
    score: "2-1",
    hook: "The Spanish bull charges at the alpine eagle.",
    story:
      "La Roja bring the unbroken charge of European champions. Austria swoop down from the Alps sharp-eyed and disciplined, hunting the one opening every eagle believes it will find.",
    youtube: "https://www.youtube.com/watch?v=PfWgttfBz1k",
    imageTeam: "Spain",
  },
  {
    ep: 88,
    home: "Portugal",
    away: "Croatia",
    stage: "Round of 32",
    date: "Jul 2, 2026",
    score: "2-1",
    hook: "The Navigator sails into the checkered fire.",
    story:
      "Portugal, heirs of the explorers, chart another dark ocean in the last thirty-two. Croatia burn back with the checkered fire that has scorched every giant foolish enough to relax.",
    youtube: "https://www.youtube.com/watch?v=PTFz5VcK6F8",
    imageTeam: "Portugal",
  },
  {
    ep: 89,
    home: "Switzerland",
    away: "Algeria",
    stage: "Round of 32",
    date: "Jul 2, 2026",
    score: "2-1",
    hook: "The mountain stands against the desert fox.",
    story:
      "Switzerland defend like the Alps themselves: silent, immense, unbreakable. Algeria race across the sand quick and clever, certain that even mountains crack if you strike the right seam.",
    youtube: "https://www.youtube.com/watch?v=aE10_vWxEbs",
    imageTeam: "Switzerland",
  },
  {
    ep: 90,
    home: "Egypt",
    away: "Australia",
    stage: "Round of 32",
    date: "Jul 3, 2026",
    score: "2-1",
    hook: "The Sphinx stares down the Southern Cross.",
    story:
      "Egypt bring the oldest crown in the game and a living legend to carry it. Australia ride in under the Southern Cross with no stars, no fear, and all heart.",
    youtube: "https://www.youtube.com/watch?v=Uqmr0LU-agU",
    imageTeam: "Egypt",
  },
  {
    ep: 91,
    home: "Argentina",
    away: "Cape Verde",
    stage: "Round of 32",
    date: "Jul 3, 2026",
    score: "2-1",
    hook: "The Sun of May meets the Blue Sharks.",
    story:
      "Argentina rise over the knockout rounds like gold over the pampa. Cape Verde, ten little islands with one giant bite, swim up from the Atlantic to hunt the champions.",
    youtube: "https://www.youtube.com/watch?v=g7P084bvJHQ",
    imageTeam: "Argentina",
  },
  {
    ep: 92,
    home: "Colombia",
    away: "Ghana",
    stage: "Round of 32",
    date: "Jul 3, 2026",
    score: "2-1",
    hook: "El Dorado's gold against the Black Star.",
    story:
      "Colombia play like the golden king of the Andes legend, all rhythm and treasure. Ghana march behind the Black Star, ready to prove that real gold is earned, never taken.",
    youtube: "https://www.youtube.com/watch?v=3ngLYrXcNs8",
    imageTeam: "Colombia",
  },
  {
    ep: 93,
    home: "Canada",
    away: "Morocco",
    stage: "Round of 16",
    date: "Jul 4, 2026",
    score: "1-2",
    hook: "The Thunderbird meets the Atlas Lion's roar.",
    story:
      "Canada spread storm-spirit wings over their first home knockout night. Down from the snow-capped peaks comes Morocco's roar — the lion that silenced giants once and hungers to do it again.",
    youtube: "https://www.youtube.com/watch?v=1o12CnTLqUQ",
    imageTeam: "Canada",
  },
  {
    ep: 94,
    home: "France",
    away: "Paraguay",
    stage: "Round of 16",
    date: "Jul 4, 2026",
    score: null,
    hook: "The golden rooster crows at the night spirit.",
    story:
      "France's rooster crows at dawn, proud and defiant as the Gauls. Paraguay's Pombéro stirs in the moonlit forest — the night spirit that loves nothing more than ruining a favourite's sleep.",
    youtube: "https://www.youtube.com/watch?v=4-tKH6DQlOI",
    imageTeam: "France",
  },
  {
    ep: 95,
    home: "Norway",
    away: "Brazil",
    stage: "Round of 16",
    date: "Jul 5, 2026",
    score: "1-2",
    hook: "Fenrir slips his chains to hunt the samba spirit.",
    story:
      "Norway unleash the great wolf of the north, prophesied to break every chain. Brazil answer with the golden spirit dancing through the Amazon canopy — and the wolf smells a wounded giant.",
    youtube: "https://www.youtube.com/watch?v=4hufXmyJzn0",
    imageTeam: "Norway",
  },
  {
    ep: 96,
    home: "Mexico",
    away: "England",
    stage: "Round of 16",
    date: "Jul 5, 2026",
    score: "1-2",
    hook: "The Feathered Serpent coils around the Three Lions.",
    story:
      "Quetzalcoatl wakes beneath the Azteca thunder for Mexico's biggest night in a generation. England's three lions have watched from the crest for eight hundred years and refuse to blink first.",
    youtube: "https://www.youtube.com/watch?v=cbbX6EJ6S_w",
    imageTeam: "Mexico",
  },
  {
    ep: 97,
    home: "Portugal",
    away: "Spain",
    stage: "Round of 16",
    date: "Jul 6, 2026",
    score: "1-2",
    hook: "The Hidden King rides out of the mist at Spain.",
    story:
      "Iberia splits in two: Portugal wait for the Hidden King to return from the fog, while Spain's raging bull charges through neighbours and legends alike. Only one crown crosses the border.",
    youtube: "https://www.youtube.com/watch?v=GzGpgwLR5C8",
    imageTeam: "Portugal",
  },
  {
    ep: 98,
    home: "USA",
    away: "Belgium",
    stage: "Round of 16",
    date: "Jul 6, 2026",
    score: "2-1",
    hook: "The hosts' talisman against the original Red Devils.",
    story:
      "Belgium have carried the Red Devil name since 1906, and the fire still burns. The USA answer with a captain-talisman and a home crowd convinced this is finally their round.",
    youtube: "https://www.youtube.com/watch?v=MuGCI3AI7Rs",
    imageTeam: "USA",
  },
  {
    ep: 99,
    home: "Argentina",
    away: "Egypt",
    stage: "Round of 16",
    date: "Jul 7, 2026",
    score: "2-1",
    hook: "Anubis weighs the genius on golden scales.",
    story:
      "Egypt summon the Warden of the Scales, who weighs every heart at the gate. Argentina send the genius himself to tip them — one more night where Messi bends the balance.",
    youtube: "https://www.youtube.com/watch?v=GD0n8FvInKg",
    imageTeam: "Argentina",
  },
  {
    ep: 100,
    home: "Switzerland",
    away: "Colombia",
    stage: "Round of 16",
    date: "Jul 7, 2026",
    score: "2-1",
    hook: "Wilhelm Tell never doubts the hundredth shot.",
    story:
      "Episode one hundred: Switzerland channel the marksman who could never miss, while Colombia's golden city glitters with Díaz and rhythm. The milestone night belongs to whoever holds their nerve longest.",
    youtube: "https://www.youtube.com/watch?v=wzCu-vitgeM",
    imageTeam: "Switzerland",
  },
  {
    ep: 101,
    home: "Spain",
    away: "Belgium",
    stage: "Quarter-final",
    date: "Jul 10, 2026",
    score: "3-1",
    hook: "El Cid rides undefeated into the quarter-finals.",
    story:
      "Spain strap the undefeated knight to his warhorse one more time and ride at Belgium's golden generation. One side is armoured in legend; the other is desperate to finally write its own.",
    youtube: "https://www.youtube.com/watch?v=rcDLZV_hhWs",
    imageTeam: "Spain",
  },
  {
    ep: 102,
    home: "France",
    away: "Morocco",
    stage: "Quarter-final",
    date: "Jul 9, 2026",
    score: "1-0",
    hook: "Roland holds the pass without blowing the horn.",
    story:
      "France hold a narrow mountain pass the way Roland once did — alone, proud, and unyielding. Morocco lay siege with the Atlas Lions' roar, hunting the opening that legend says never comes.",
    youtube: "https://www.youtube.com/watch?v=w1GZnvQgw_0",
    imageTeam: "France",
  },
  {
    ep: 103,
    home: "Norway",
    away: "England",
    stage: "Quarter-final",
    date: "Jul 11, 2026",
    score: "1-1",
    hook: "The World Serpent closes its coil on the lions.",
    story:
      "Jörmungandr wraps the whole world in one unbroken circle, and Norway believe Haaland is its bite. England's lions have out-stared every myth before — but the serpent has never felt this real.",
    youtube: "https://www.youtube.com/watch?v=04MKt0r5UXw",
    imageTeam: "Norway",
  },
  {
    ep: 104,
    home: "Argentina",
    away: "Switzerland",
    stage: "Quarter-final",
    date: "Jul 11, 2026",
    score: "3-2",
    hook: "Gauchito Gil grants miracles at the final breath.",
    story:
      "Argentina pray at the little red shrines of the gaucho saint who grants the impossible at the death. Switzerland bring the coldest red wall in the tournament and a habit of going to the wire.",
    youtube: "https://www.youtube.com/watch?v=QXIKEV5qxYo",
    imageTeam: "Argentina",
  },
];

export const YOUTUBE_LEGEND_BONUS_VIDEOS: YouTubeLegendBonusVideo[] = [
  {
    id: "bonus-lukaku-promise",
    episode: 901,
    episodeLabel: "Bonus Legend",
    title: "Lukaku: The Promise",
    subtitle: "Legend bonus card",
    teams: "Belgium",
    story:
      "A striker carries every miss, every chant, and every promise into one last Belgium chapter. This bonus card belongs to the player who keeps standing back up.",
    youtube: "https://www.youtube.com/watch?v=Yo4q-_iHoKM",
    imageTeam: "Morocco",
  },
  {
    id: "bonus-luis-diaz",
    episode: 902,
    episodeLabel: "Bonus Legend",
    title: "Luis Diaz",
    subtitle: "Legend bonus card",
    teams: "Colombia",
    story:
      "Luis Diaz plays like a storm with a smile: fearless, direct, and impossible to ignore. This bonus card turns Colombia's wing into a collectible spark.",
    youtube: "https://www.youtube.com/watch?v=3AuPzxScrac",
    imageTeam: "Canada",
  },
  {
    id: "bonus-world-cup-secrets",
    episode: 903,
    episodeLabel: "Bonus Legend",
    title: "World Cup Monopoly",
    subtitle: "Legend bonus card",
    teams: "World Cup history",
    story:
      "The Monopoly card follows the strange truths, power moves, and hidden football business that make the World Cup bigger than ninety minutes.",
    youtube: "https://www.youtube.com/watch?v=zb4W9KkVESU",
    alternateYoutube: [
      "https://www.youtube.com/watch?v=0oHkstIXqjk",
      "https://www.youtube.com/watch?v=9EzJmef1QJI",
      "https://www.youtube.com/watch?v=Eyr32VpWKdY",
      "https://www.youtube.com/watch?v=qP2qU-JAr6A",
      "https://www.youtube.com/watch?v=e96tg1mpKHo",
    ],
    imageTeam: "Mexico",
  },
  {
    id: "bonus-launch-film",
    episode: 900,
    episodeLabel: "Launch Film",
    kind: "series",
    title: "WorldCup26 Launch",
    subtitle: "Series launch card",
    teams: "WorldCup26 Legends",
    story:
      "The launch card opens the whole collection: nations, myths, rivalries, and a prediction game built around stories before every match.",
    youtube: "https://www.youtube.com/watch?v=NGyPLObwq4c",
    imageTeam: "USA",
  },
];

export const YOUTUBE_DID_YOU_KNOW_SHORTS: YouTubeDidYouKnowShort[] = [
  {
    id: "short-gaetjens-vanished",
    episode: 950,
    episodeLabel: "Did You Know? Short",
    title: "The Vanished Hero",
    subtitle: "Did You Know? Short · Joe Gaetjens",
    teams: "USA 1-0 England · 1950",
    story:
      "A part-time American dishwasher named Joe Gaetjens threw himself at a cross and scored the header that beat mighty England. He went home to Haiti a hero. Then the dictatorship made him disappear. No grave. No body. No answers.",
    youtube: "https://www.youtube.com/shorts/bSFDrewxg9s",
    imageTeam: "USA",
  },
  {
    id: "short-garrincha-broken-magic",
    episode: 951,
    episodeLabel: "Did You Know? Short",
    title: "The Broken Boy Who Became Magic",
    subtitle: "Did You Know? Short · Garrincha",
    teams: "Brazil · World Cup 1962",
    story:
      "Doctors thought Garrincha's crooked legs should stop him from walking. Instead, those impossible legs confused defenders, carried Brazil after Pele's injury, and made him the Joy of the People.",
    youtube: "https://www.youtube.com/shorts/0rmcr7dmwSc",
    imageTeam: "Brazil",
  },
  {
    id: "short-carbajal-five-world-cups",
    episode: 952,
    episodeLabel: "Did You Know? Short",
    title: "The Keeper Who Hid in Goal",
    subtitle: "Did You Know? Short · Antonio Carbajal",
    teams: "Mexico · 5 World Cups",
    story:
      "Antonio Carbajal became a goalkeeper so he could see his father coming and run before getting caught playing football. That hiding place became the first five-World-Cup career.",
    youtube: "https://www.youtube.com/shorts/rqQ_xVUzic8",
    imageTeam: "Mexico",
  },
  {
    id: "short-socrates-sunday",
    episode: 953,
    episodeLabel: "Did You Know? Short",
    title: "The Death He Predicted",
    subtitle: "Did You Know? Short · Socrates",
    teams: "Brazil · 1982",
    story:
      "Socrates said he wanted to die on a Sunday while Corinthians won a title. On December 4, 2011, he passed away, and Corinthians became champions the same day.",
    youtube: "https://www.youtube.com/shorts/e3-SVYS33xk",
    imageTeam: "Brazil",
  },
  {
    id: "short-milla-corner-flag",
    episode: 954,
    episodeLabel: "Did You Know? Short",
    title: "The Dancing Lion",
    subtitle: "Did You Know? Short · Roger Milla",
    teams: "Cameroon · 1990",
    story:
      "Roger Milla was supposed to be too old for a World Cup comeback. Instead, at thirty-eight, he danced by the corner flag and made Cameroon feel like the center of football.",
    youtube: "https://www.youtube.com/shorts/a4Za3AjOeEE",
    imageTeam: "Cameroon",
  },
  {
    id: "short-laurent-first-goal",
    episode: 955,
    episodeLabel: "Did You Know? Short",
    title: "The First Goal",
    subtitle: "Did You Know? Short · Lucien Laurent",
    teams: "France · 1930",
    story:
      "Lucien Laurent was a factory worker who became the first goal scorer in World Cup history. One swing of his boot made him the first name in the tournament's story.",
    youtube: "https://www.youtube.com/shorts/Wj-k6syhVcY",
    imageTeam: "France",
  },
  {
    id: "short-escobar-own-goal",
    episode: 956,
    episodeLabel: "Did You Know? Short",
    title: "The Gentleman",
    subtitle: "Did You Know? Short · Andres Escobar",
    teams: "Colombia · 1994",
    story:
      "Andres Escobar scored an own goal at the World Cup and answered with grace instead of excuses. Days later, football learned how cruel a story can become.",
    youtube: "https://www.youtube.com/shorts/ZUsFa2mNki0",
    imageTeam: "Colombia",
  },
  {
    id: "short-yashin-black-spider",
    episode: 957,
    episodeLabel: "Did You Know? Short",
    title: "The Black Spider",
    subtitle: "Did You Know? Short · Lev Yashin",
    teams: "Soviet Union · Ballon d'Or",
    story:
      "Lev Yashin nearly chose ice hockey, then became the only goalkeeper to win the Ballon d'Or. They called him the Black Spider because his saves seemed to come from everywhere.",
    youtube: "https://www.youtube.com/shorts/N7wiebdbI-E",
    imageTeam: "Russia",
  },
  {
    id: "short-monti-two-finals",
    episode: 958,
    episodeLabel: "Did You Know? Short",
    title: "Two Nations",
    subtitle: "Did You Know? Short · Luis Monti",
    teams: "Argentina and Italy · 1930/1934",
    story:
      "Luis Monti played World Cup finals for two different countries. One final ended in fear and defeat; the next ended with a winner's medal for another nation.",
    youtube: "https://www.youtube.com/shorts/VeB_RKVhPv0",
    imageTeam: "Argentina",
  },
  {
    id: "short-tostao-eyes",
    episode: 959,
    episodeLabel: "Did You Know? Short",
    title: "Eyes of a Champion",
    subtitle: "Did You Know? Short · Tostao",
    teams: "Brazil · 1970",
    story:
      "Tostao nearly lost his sight before the 1970 World Cup. He came back anyway, helped Brazil win the most beautiful title, and turned fragile vision into genius.",
    youtube: "https://www.youtube.com/shorts/KZ15CaO-y4E",
    imageTeam: "Brazil",
  },
  {
    id: "short-castro-one-armed-champion",
    episode: 960,
    episodeLabel: "Did You Know? Short",
    title: "The One-Armed Champion",
    subtitle: "Did You Know? Short · Hector Castro",
    teams: "Uruguay · 1930",
    story:
      "Hector Castro lost his right hand as a boy, then helped Uruguay win the first World Cup. He scored in the 1930 final against Argentina and became the champion no one could write off.",
    youtube: "https://www.youtube.com/shorts/Mv-GBCDS-EQ",
    imageTeam: "Uruguay",
  },
  {
    id: "short-pak-secret-hero",
    episode: 961,
    episodeLabel: "Did You Know? Short",
    title: "The Secret Hero",
    subtitle: "Did You Know? Short · Pak Doo-ik",
    teams: "North Korea 1-0 Italy · 1966",
    story:
      "Pak Doo-ik was a print-factory worker when North Korea arrived at the 1966 World Cup as outsiders. His goal beat Italy, sent shock through football, and made Middlesbrough fall in love with a team that vanished from the world stage.",
    youtube: "https://www.youtube.com/shorts/_kbLwv0R38k",
    imageTeam: "North Korea",
  },
];

export function youtubeForEpisode(episode: number) {
  return YOUTUBE_LEGEND_EPISODES.find((prediction) => prediction.ep === episode)?.youtube ?? null;
}
