var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jb~93e._.js")
R.c("server/chunks/ssr/src_lib_supabase_ts_12ti~96._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_000r43q.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tj61ge._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lkl6m-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0i_._k3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yvrcis._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_page_actions_0ycnu8f.js")
R.m(93210)
module.exports=R.m(93210).exports
