var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/wallet/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cf63k2._.js")
R.c("server/chunks/ssr/src_lib_paid-action-gates_ts_02f1h.h._.js")
R.c("server/chunks/ssr/src_lib_supabase_ts_12ti~96._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0f9e42v.js")
R.c("server/chunks/ssr/[root-of-the-server]__00~ecql._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lkl6m-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0i_._k3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yvrcis._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_wallet_page_actions_0y35bmh.js")
R.m(51415)
module.exports=R.m(51415).exports
