var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/terms/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gc1tp0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0rynfcj.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tj61ge._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lkl6m-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0i_._k3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yvrcis._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_terms_page_actions_0a8-y6r.js")
R.m(44041)
module.exports=R.m(44041).exports
