var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/referrals/me/route.js")
R.c("server/chunks/src_app_api_referrals_me_route_ts_0n61slv._.js")
R.c("server/chunks/node_modules_next_0qslkfn._.js")
R.c("server/chunks/node_modules_@supabase_postgrest-js_dist_index_mjs_0uel2xe._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_00jw3pg._.js")
R.c("server/chunks/node_modules_0_hdopb._.js")
R.c("server/chunks/[root-of-the-server]__0.f8izv._.js")
R.c("server/chunks/_next-internal_server_app_api_referrals_me_route_actions_0l2u82c.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/referrals/me/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/referrals/me/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
