var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/entries/route.js")
R.c("server/chunks/[root-of-the-server]__05knvy2._.js")
R.c("server/chunks/src_lib_0m5-kvz._.js")
R.c("server/chunks/src_lib_0z4z~ld._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_03-wy2n.js")
R.c("server/chunks/_0558vrh._.js")
R.c("server/chunks/_next-internal_server_app_api_entries_route_actions_0i4smbi.js")
R.m(67076)
module.exports=R.m(67076).exports
