var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/me/standing/route.js")
R.c("server/chunks/src_app_api_me_standing_route_ts_0w9ff_o._.js")
R.c("server/chunks/node_modules_next_08b_xod._.js")
R.c("server/chunks/node_modules_@supabase_postgrest-js_dist_index_mjs_0uel2xe._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_00jw3pg._.js")
R.c("server/chunks/node_modules_0_hdopb._.js")
R.c("server/chunks/[root-of-the-server]__06a~cd4._.js")
R.c("server/chunks/_next-internal_server_app_api_me_standing_route_actions_0lsn8vn.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/me/standing/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/me/standing/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
