var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/deposits/claims/route.js")
R.c("server/chunks/[root-of-the-server]__0l_lrgo._.js")
R.c("server/chunks/src_lib_0m5-kvz._.js")
R.c("server/chunks/src_lib_0z4z~ld._.js")
R.c("server/chunks/[root-of-the-server]__0j8-xkl._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_137s.3k.js")
R.c("server/chunks/_0558vrh._.js")
R.c("server/chunks/_next-internal_server_app_api_deposits_claims_route_actions_0ruw24b.js")
R.m(84681)
module.exports=R.m(84681).exports
