#!/usr/bin/env python3
"""
World Cup 2026 — Match Presentation Builder

Builds the full match presentation video from a presentation config:
  title cards (design-system styled, rendered with Pillow + Inter),
  player character videos with lower-third name overlays,
  supporter stills with a Ken Burns move,
  a story interlude card, a closing CTA card,
  and (when generated) the Brian/ElevenLabs narration track.

Design tokens follow docs/DESIGN_SYSTEM.md:
  ink #0c1d1a, primary green #106b4f, gold #c9942e, border #d8e3df, Inter only.

Usage:
    python3 make_match_presentation.py Mexico-vs-South-Africa
    python3 make_match_presentation.py Mexico-vs-South-Africa --keep-temp

Narration: if scripts/narration/audio/<Match>/line_XX.mp3 exist (generated by
generate_story_audio.mjs), they are placed at the timestamps declared in
scripts/narration/<Match>.json and mixed over the ambient track.
"""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

SCRIPTS_DIR = Path(__file__).resolve().parent
CONTENT_ROOT = SCRIPTS_DIR.parent
VIDEOS_DIR = CONTENT_ROOT / "videos"
IMAGES_DIR = CONTENT_ROOT / "images"
OUTPUT_DIR = CONTENT_ROOT / "match_videos"
FONTS_DIR = SCRIPTS_DIR / "fonts"

W, H = 1280, 720
FPS = 24

INK = (12, 29, 26)
GREEN = (16, 107, 79)
GREEN_TINT = (229, 243, 238)
GOLD = (201, 148, 46)
WHITE = (255, 255, 255)
MUTED = (147, 169, 162)
BORDER = (216, 227, 223)

CARD_SECONDS = {"open": 6, "team": 3, "story": 6, "cta": 6}
SUPPORTER_SECONDS = 4


def font(weight: str, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(str(FONTS_DIR / f"Inter-{weight}.ttf"), size)


def run(cmd: list[str]) -> None:
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"ffmpeg failed:\n{' '.join(cmd)}\n{result.stderr[-2000:]}")


def text_w(draw: ImageDraw.ImageDraw, text: str, f: ImageFont.FreeTypeFont) -> int:
    left, _, right, _ = draw.textbbox((0, 0), text, font=f)
    return right - left


def centered(draw: ImageDraw.ImageDraw, y: int, text: str, f: ImageFont.FreeTypeFont, fill, tracking: int = 0):
    if tracking:
        widths = [text_w(draw, ch, f) + tracking for ch in text]
        total = sum(widths) - tracking
        x = (W - total) // 2
        for ch, w in zip(text, widths):
            draw.text((x, y), ch, font=f, fill=fill)
            x += w
    else:
        draw.text(((W - text_w(draw, text, f)) // 2, y), text, font=f, fill=fill)


def base_card() -> tuple[Image.Image, ImageDraw.ImageDraw]:
    img = Image.new("RGB", (W, H), INK)
    draw = ImageDraw.Draw(img)
    # Restrained panel frame, matching the app's bordered-panel language.
    draw.rounded_rectangle([40, 40, W - 40, H - 40], radius=8, outline=BORDER + (60,), width=1)
    return img, draw


def gold_rule(draw: ImageDraw.ImageDraw, y: int, width: int = 120):
    draw.rectangle([(W - width) // 2, y, (W + width) // 2, y + 3], fill=GOLD)


def render_open_card(cfg: dict, path: Path):
    img, draw = base_card()
    centered(draw, 130, cfg["competition"], font("SemiBold", 30), GOLD, tracking=8)
    gold_rule(draw, 185)
    centered(draw, 240, cfg["title"], font("Black", 72), WHITE)
    centered(draw, 350, cfg["tagline"], font("SemiBold", 26), GREEN_TINT, tracking=6)
    centered(draw, 430, cfg["subtitle"], font("Regular", 24), MUTED)
    centered(draw, 540, "OFFICIAL MATCH PRESENTATION", font("SemiBold", 16), MUTED, tracking=4)
    img.save(path)


def render_team_card(team: dict, cfg: dict, path: Path):
    img, draw = base_card()
    centered(draw, 150, cfg["competition"], font("SemiBold", 20), MUTED, tracking=6)
    centered(draw, 240, team["name"], font("Black", 84), WHITE)
    gold_rule(draw, 360)
    centered(draw, 400, team["nickname"], font("SemiBold", 34), GOLD, tracking=8)
    names = "  ·  ".join(p["name"] for p in team["players"])
    centered(draw, 500, names, font("Regular", 20), GREEN_TINT)
    img.save(path)


def render_story_card(cfg: dict, path: Path):
    img, draw = base_card()
    centered(draw, 140, cfg["story_quote_label"], font("SemiBold", 28), GOLD, tracking=8)
    gold_rule(draw, 195)
    # Wrap the quote to ~46 chars per line.
    words, lines, line = cfg["story_quote"].split(), [], ""
    for w_ in words:
        if len(line) + len(w_) + 1 > 46:
            lines.append(line)
            line = w_
        else:
            line = f"{line} {w_}".strip()
    lines.append(line)
    y = 260
    for ln in lines:
        centered(draw, y, ln, font("Regular", 30), WHITE)
        y += 48
    img.save(path)


def render_cta_card(cfg: dict, path: Path):
    img, draw = base_card()
    draw.rounded_rectangle([340, 200, W - 340, 380], radius=8, fill=GREEN)
    centered(draw, 250, cfg["cta_title"], font("Black", 54), WHITE)
    centered(draw, 440, cfg["cta_subtitle"], font("SemiBold", 30), GOLD)
    centered(draw, 540, cfg["competition"], font("SemiBold", 18), MUTED, tracking=6)
    img.save(path)


def render_lower_third(player: dict, team: dict, path: Path):
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    name_f, role_f, team_f = font("Bold", 36), font("Regular", 22), font("SemiBold", 18)
    pad, x0, y0 = 24, 64, H - 150
    bar_w = max(text_w(draw, player["name"], name_f), text_w(draw, player["role"], role_f)) + pad * 2
    draw.rounded_rectangle([x0, y0, x0 + bar_w, y0 + 104], radius=8, fill=GREEN + (230,))
    draw.rectangle([x0, y0, x0 + 6, y0 + 104], fill=GOLD)
    draw.text((x0 + pad, y0 + 12), player["name"], font=name_f, fill=WHITE)
    draw.text((x0 + pad, y0 + 62), player["role"], font=role_f, fill=GREEN_TINT)
    tw = text_w(draw, f"{team['name']} · {team['nickname']}", team_f)
    draw.text((W - 64 - tw, y0 + 70), f"{team['name']} · {team['nickname']}", font=team_f, fill=GOLD + (255,))
    img.save(path)


def render_supporter_caption(caption: str, path: Path):
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    f = font("SemiBold", 26)
    tw = text_w(draw, caption, f)
    x0, y0 = (W - tw) // 2 - 24, H - 110
    draw.rounded_rectangle([x0, y0, x0 + tw + 48, y0 + 56], radius=8, fill=INK + (210,))
    draw.text((x0 + 24, y0 + 12), caption, font=f, fill=WHITE)
    img.save(path)


SILENT_AUDIO = ["-f", "lavfi", "-i", "anullsrc=channel_layout=stereo:sample_rate=44100"]
ENC = ["-c:v", "libx264", "-crf", "21", "-pix_fmt", "yuv420p", "-r", str(FPS),
       "-c:a", "aac", "-b:a", "160k", "-ar", "44100", "-ac", "2"]


def card_segment(png: Path, seconds: int, out: Path):
    fade_out = seconds - 0.5
    run(["ffmpeg", "-y", "-loop", "1", "-t", str(seconds), "-i", str(png), *SILENT_AUDIO,
         "-vf", f"fade=t=in:st=0:d=0.5,fade=t=out:st={fade_out}:d=0.5",
         "-t", str(seconds), "-shortest", *ENC, str(out)])


def player_segment(video: Path, overlay_png: Path, out: Path):
    has_audio = b"Audio" in subprocess.run(["ffmpeg", "-i", str(video)], capture_output=True).stderr
    inputs = ["-i", str(video), "-i", str(overlay_png)]
    if not has_audio:
        inputs += SILENT_AUDIO
    fc = (f"[0:v]scale={W}:{H}:force_original_aspect_ratio=decrease,"
          f"pad={W}:{H}:(ow-iw)/2:(oh-ih)/2:color=0x0c1d1a,fps={FPS}[v0];"
          f"[v0][1:v]overlay=0:0:enable='gte(t,0.6)'[v]")
    audio_map = ["-map", "0:a"] if has_audio else ["-map", "2:a", "-shortest"]
    run(["ffmpeg", "-y", *inputs, "-filter_complex", fc, "-map", "[v]", *audio_map, *ENC, str(out)])


def supporter_segment(image: Path, caption_png: Path, seconds: int, out: Path):
    frames = seconds * FPS
    fc = (f"[0:v]scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080,"
          f"zoompan=z='1+0.08*on/{frames}':x='iw/2-(iw/zoom)/2':y='ih/2-(ih/zoom)/2'"
          f":d={frames}:s={W}x{H}:fps={FPS}[v0];"
          f"[v0][1:v]overlay=0:0[v1];[v1]fade=t=in:st=0:d=0.4,fade=t=out:st={seconds - 0.4}:d=0.4[v]")
    run(["ffmpeg", "-y", "-loop", "1", "-t", str(seconds), "-i", str(image), "-i", str(caption_png),
         *SILENT_AUDIO, "-filter_complex", fc, "-map", "[v]", "-map", "2:a",
         "-t", str(seconds), "-shortest", *ENC, str(out)])


def mux_narration(video: Path, match: str, out: Path) -> bool:
    narration_file = SCRIPTS_DIR / "narration" / f"{match}.json"
    audio_dir = SCRIPTS_DIR / "narration" / "audio" / match
    if not narration_file.exists() or not audio_dir.exists():
        return False
    lines = json.loads(narration_file.read_text())["lines"]
    mp3s = [audio_dir / f"line_{i:02d}.mp3" for i in range(len(lines))]
    if not all(p.exists() for p in mp3s):
        return False

    inputs = ["-i", str(video)]
    for p in mp3s:
        inputs += ["-i", str(p)]
    chains, mix = [], []
    for i, line in enumerate(lines):
        delay = int(float(line["at"]) * 1000)
        chains.append(f"[{i + 1}:a]adelay={delay}|{delay}[vo{i}]")
        mix.append(f"[vo{i}]")
    # Mix: ambient track (ducked) + all VO lines at their timestamps.
    fc = ";".join(chains) + f";[0:a]volume=0.30[amb];[amb]{''.join(mix)}amix=inputs={len(mix) + 1}:normalize=0[a]"
    run(["ffmpeg", "-y", *inputs, "-filter_complex", fc,
         "-map", "0:v", "-map", "[a]", "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", str(out)])
    return True


def main():
    parser = argparse.ArgumentParser(description="Build a World Cup match presentation video")
    parser.add_argument("match", help="Match name, e.g. Mexico-vs-South-Africa")
    parser.add_argument("--keep-temp", action="store_true")
    args = parser.parse_args()

    cfg_file = SCRIPTS_DIR / "presentations" / f"{args.match}.json"
    if not cfg_file.exists():
        print(f"ERROR: no presentation config at {cfg_file}")
        sys.exit(1)
    cfg = json.loads(cfg_file.read_text())

    tmp = Path(tempfile.mkdtemp(prefix=f"{args.match}-"))
    segments: list[Path] = []

    def add_card(kind: str, render, *render_args):
        png = tmp / f"{kind}.png"
        render(*render_args, png)
        seg = tmp / f"seg_{len(segments):02d}_{kind}.mp4"
        card_segment(png, CARD_SECONDS[kind.split("_")[0]], seg)
        segments.append(seg)

    print(f"Building {args.match} presentation in {tmp}")
    add_card("open", render_open_card, cfg)

    for side in ("team_a", "team_b"):
        team = cfg[side]
        add_card(f"team_{side}", render_team_card, team, cfg)
        for p in team["players"]:
            video = VIDEOS_DIR / team["folder"] / p["file"]
            still = IMAGES_DIR / team["folder"] / f"{Path(p['file']).stem}.png"
            lt = tmp / f"lt_{side}_{p['file']}.png"
            render_lower_third(p, team, lt)
            seg = tmp / f"seg_{len(segments):02d}_{Path(p['file']).stem}.mp4"
            if video.exists():
                player_segment(video, lt, seg)
                print(f"  + {team['name']}: {p['name']}")
            elif still.exists():
                # Video generation blocked/unavailable — Ken Burns the character still.
                supporter_segment(still, lt, 6, seg)
                print(f"  + {team['name']}: {p['name']} (still fallback)")
            else:
                print(f"  !! no video or still for {p['name']} — skipped")
                continue
            segments.append(seg)
        supporter = IMAGES_DIR / "Supporters" / team["folder"] / team["supporter_image"]
        if supporter.exists():
            cap = tmp / f"cap_{side}.png"
            render_supporter_caption(team["supporter_caption"], cap)
            seg = tmp / f"seg_{len(segments):02d}_supporter_{side}.mp4"
            supporter_segment(supporter, cap, SUPPORTER_SECONDS, seg)
            segments.append(seg)
            print(f"  + {team['name']}: supporters")
        else:
            print(f"  !! missing supporter image {supporter} — skipped")
        if side == "team_a":
            add_card("story", render_story_card, cfg)

    add_card("cta", render_cta_card, cfg)

    concat_file = tmp / "concat.txt"
    concat_file.write_text("\n".join(f"file '{s}'" for s in segments))
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    silent_out = tmp / f"{args.match}_silent.mp4"
    run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(concat_file),
         *ENC, "-movflags", "+faststart", str(silent_out)])

    final = OUTPUT_DIR / f"{args.match}.mp4"
    if mux_narration(silent_out, args.match, final):
        print(f"Narration muxed (Brian voiceover).")
    else:
        shutil.copy(silent_out, final)
        print("No narration audio found — built without voiceover. "
              "Run generate_story_audio.mjs, then re-run this script to add it.")

    if not args.keep_temp:
        shutil.rmtree(tmp, ignore_errors=True)
    dur = subprocess.run(["ffmpeg", "-i", str(final)], capture_output=True, text=True).stderr
    dur_line = next((line.strip() for line in dur.splitlines() if "Duration" in line), "")
    print(f"DONE: {final}\n  {dur_line}")


if __name__ == "__main__":
    main()
